import jsPDF from "jspdf";
import { autoTable } from "jspdf-autotable";

const generateTicketPdf = (ticketData) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(18);
  doc.text("Mock Train Ticket", 14, 20);

  // Train info table
  autoTable(doc, {
    startY: 30,
    head: [["Field", "Value"]],
    body: [
      ["Train Number", ticketData?.train?.train_number],
      ["Train Name", ticketData?.train?.train_name],
      ["From", ticketData?.train?.from],
      ["To", ticketData?.train?.to],
      ["Departure", ticketData?.train?.departure],
      ["Arrival", ticketData?.train?.arrival],
      ["Duration", ticketData?.train?.duration],
      ["PNR", ticketData?.train?.pnr],
    ],
  });

  // Passenger Details Table
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Name", "Age", "Gender", "Type"]],
    body: ticketData?.passengers?.map((p) => [p.name, p.age, p.gender, p.type]),
  });

  // Footer
  doc.setFontSize(10);
  doc.text(
    "Generated by ServerPe Mock Booking",
    14,
    doc.internal.pageSize.height - 10
  );

  // Save
  doc.save("MockTicket.pdf");
};
export default generateTicketPdf;
